//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpleadosEDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados_Antiguedad_Estadisticas
    {
        public int ANTIGUEDAD_ID { get; set; }
        public Nullable<int> Empleado_ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Extra { get; set; }
        public Nullable<int> Bajas_Laborales { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
