//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpleadosEDM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmpleadosEDMEntities : DbContext
    {
        public EmpleadosEDMEntities()
            : base("name=EmpleadosEDMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleado_Detalles> Empleado_Detalles { get; set; }
        public virtual DbSet<Empleado_Experiencia_Estadisticas> Empleado_Experiencia_Estadisticas { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Empleados_Antiguedad_Estadisticas> Empleados_Antiguedad_Estadisticas { get; set; }
    }
}
